repos:
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.4
    hooks:
      - id: shell-lint

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.11.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate_no_variables

