version: 2
jobs:
  test:
    working_directory: ~/stage/test2
    docker:
      - image: circleci/terraform:0.11.3
    steps:
      - checkout
      - run:
          name: Terraform init
          command: version
